checks:
  php: true
filter:
  excluded_paths:
    - bin/
    - generated/
    - test/
    - tools/
build:
  environment:
    php:
      version: 7.4
  nodes:
    analysis: # https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/#security-analysis
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    coverage:    # https://scrutinizer-ci.com/docs/build/code_coverage
      dependencies:
        before:
          - pecl install pcov
          - php phive.phar --no-progress install --copy --force-accept-unsigned --trust-gpg-keys 31C7E470E2138192,4AA394086372C20A,0F9684B8B16B7AB0
      tests:
        override:
          -
            command: composer run test-full
            coverage:
              file: report/coverage/clover.xml
              format: php-clover
