checks:
  php: true
filter:
  excluded_paths:
    - bin/*
    - generated/*
    - test/*
build:
  environment:
    php:
      version: 7.3
  tests:
    override:
      -
        command: composer test
        coverage:
          file: report/coverage/clover.xml
          format: php-clover
