language: generic
sudo: required
service:
  - docker
env:
  - TRAVIS_PHP_VERSION=5.6
  - TRAVIS_PHP_VERSION=5.5
  - TRAVIS_PHP_VERSION=5.4
  - TRAVIS_PHP_VERSION=5.3
  - TRAVIS_PHP_VERSION=5.2
before_install:
  - docker build -t xkerman/php-$TRAVIS_PHP_VERSION -f docker/Dockerfile.$TRAVIS_PHP_VERSION docker
install:
  - curl -s -O https://getcomposer.org/composer.phar
  - rm composer.lock
script:
  - if [ $TRAVIS_PHP_VERSION != '5.2' ]; then docker run -v $(pwd):/tmp  -w /tmp xkerman/php-$TRAVIS_PHP_VERSION sh -c 'php composer.phar install --no-interaction && php composer.phar test'; fi
  - if [ $TRAVIS_PHP_VERSION = '5.2' ]; then docker run -v $(pwd):/tmp  -w /tmp xkerman/php-$TRAVIS_PHP_VERSION sh -c 'php /usr/local/php/phpunit/phpunit.php --configuration phpunit.php52.xml;'; fi
after_success:
  - bash <(curl -s https://codecov.io/bash) -c -F $(echo $TRAVIS_PHP_VERSION | sed -e 's/\./_/g')
