language: php
sudo: required
service:
  - docker
env:
  -
    PHP_VERSION=5.6
    DOCKER_IMAGE='php:5.6-cli'
    COMPOSER_VERSION=1.5.1
before_install:
  - docker pull $DOCKER_IMAGE
install:
  - curl -s -O https://getcomposer.org/download/$COMPOSER_VERSION/composer.phar
script:
  - docker run -v $(pwd):/tmp sh -c 'cd /tmp && php composer.phar install && php composer.phar test'
