language: php
sudo: false
cache:
  directories:
    - vendor
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      php: '5.6'
    - os: linux
      dist: trusty
      sudo: false
      php: '5.5'
    - os: linux
      dist: trusty
      sudo: false
      php: '5.4'
    - os: linux
      sudo: false
      php: '5.3'
    - os: linux
      sudo: false
      php: '5.2'
    - os: linux
      dist: trusty
      sudo: false
      php: 'hhvm'

install:
  - rm composer.lock && composer install --no-interaction || true
script:
  - bash travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
