language: php
sudo: false
cache:
  directories:
    - vendor
php:
  - '5.6'
  - '5.5'
  - '5.4'
  - '5.3'
  - '5.2'
  - hhvm
install:
  - rm composer.lock && composer install --no-interaction || true
script:
  - bash travis.sh
