language: generic
sudo: required
service:
  - docker
env:
  -
    TRAVIS_PHP_VERSION=5.6
    COMPOSER_VERSION=1.5.1
  -
    TRAVIS_PHP_VERSION=5.5
    COMPOSER_VERSION=1.5.1
  -
    TRAVIS_PHP_VERSION=5.4
    COMPOSER_VERSION=1.5.1
before_install:
  - docker build -t xkerman/php-$TRAVIS_PHP_VERSION -f docker/Dockerfile.$TRAVIS_PHP_VERSION docker
install:
  - curl -s -O https://getcomposer.org/download/$COMPOSER_VERSION/composer.phar
  - rm composer.lock
script:
  - docker run -v $(pwd):/tmp xkerman/php-$TRAVIS_PHP_VERSION -w /tmp sh -c 'php composer.phar install --no-interaction && php composer.phar test'
after_success:
  - bash <(curl -s https://codecov.io/bash) -c -F $(echo $TRAVIS_PHP_VERSION | sed -e 's/\./_/g')
