FROM lavoweb/php-5.4

RUN echo "deb http://deb.debian.org/debian jessie main" > /etc/apt/sources.list && \
    echo "deb http://security.debian.org jessie/updates main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install unzip

RUN pecl install xdebug-2.4.1 && docker-php-ext-enable xdebug
